// Code generated by goctl. DO NOT EDIT.
// Source: users.proto

package server

import (
	"context"

	"github.com/andres06-hub/users/internal/logic"
	"github.com/andres06-hub/users/internal/svc"
	"github.com/andres06-hub/users/users"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	users.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) CreateUser(ctx context.Context, in *users.CreateUserRequest) (*users.Response, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UsersServer) FindUser(ctx context.Context, in *users.FindUserRequest) (*users.Response, error) {
	l := logic.NewFindUserLogic(ctx, s.svcCtx)
	return l.FindUser(in)
}
