// Code generated by goctl. DO NOT EDIT.
// Source: users.proto

package server

import (
	"context"

	"github.com/andres06-hub/users/internal/logic"
	"github.com/andres06-hub/users/internal/svc"
	"github.com/andres06-hub/users/users"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	users.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) Ping(ctx context.Context, in *users.Request) (*users.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
