// Code generated by goctl. DO NOT EDIT.
// Source: users.proto

package usersclient

import (
	"context"

	"github.com/andres06-hub/users/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateUserRequest = users.CreateUserRequest
	Data              = users.Data
	FindUserRequest   = users.FindUserRequest
	Response          = users.Response

	Users interface {
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*Response, error)
		FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*Response, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUsers) FindUser(ctx context.Context, in *FindUserRequest, opts ...grpc.CallOption) (*Response, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.FindUser(ctx, in, opts...)
}
