// Code generated by goctl. DO NOT EDIT.
// Source: users.proto

package usersclient

import (
	"context"

	"github.com/andres06-hub/users/users"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = users.Request
	Response = users.Response

	Users interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := users.NewUsersClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
